catalog:
  '@biomejs/biome': 2.4.2
  '@commitlint/cli': 20.4.1
  '@commitlint/config-conventional': 20.4.1
  lefthook: 2.1.1
  typescript: 5.9.3

catalogs:
  nextjs:
    next: 16.1.6
  styles:
    '@tailwindcss/postcss': 4.2.1
    tailwindcss: 4.2.1
  types:
    '@types/node': 25.3.0
    '@types/react': 19.2.14
    '@types/react-dom': 19.2.3
  ui:
    class-variance-authority: 0.7.1
    clsx: 2.1.1
    lucide-react: 0.575.0
    radix-ui: 1.4.3
    react: 19.2.4
    react-dom: 19.2.4
    tailwind-merge: 3.5.0
    tw-animate-css: 1.4.0
  web3:
    viem: 2.46.3
    wagmi: 3.5.0

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
